{
  "affected": [
    {
      "database_specific": {
        "source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/newpipv3/MAL-2024-10877.json"
      },
      "package": {
        "ecosystem": "PyPI",
        "name": "newpipv3",
        "purl": "pkg:pypi/newpipv3"
      },
      "versions": [
        "0.1.0"
      ]
    }
  ],
  "credits": [
    {
      "contact": [
        "https://github.com/ossf/package-analysis",
        "https://openssf.slack.com/channels/package_analysis"
      ],
      "name": "OpenSSF: Package Analysis",
      "type": "FINDER"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "import_time": "2024-11-22T10:06:16.036579533Z",
        "modified_time": "2024-11-22T09:48:50Z",
        "sha256": "54fac2a807bae6742d82c86f55d97a1b4a810e42ee3b0b9dcb0c981c36ab712d",
        "source": "ossf-package-analysis",
        "versions": [
          "0.1.0"
        ]
      }
    ]
  },
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n\n## Source: ossf-package-analysis (54fac2a807bae6742d82c86f55d97a1b4a810e42ee3b0b9dcb0c981c36ab712d)\nThe OpenSSF Package Analysis project identified 'newpipv3' @ 0.1.0 (pypi) as malicious.\n\nIt is considered malicious because:\n\n- The package communicates with a domain associated with malicious activity.\n\n- The package executes one or more commands associated with malicious behavior.\n",
  "id": "MAL-2024-10877",
  "modified": "2024-11-22T09:48:50Z",
  "published": "2024-11-22T09:48:50Z",
  "schema_version": "1.6.0",
  "summary": "Malicious code in newpipv3 (PyPI)"
}