{
  "affected": [
    {
      "database_specific": {
        "source": "https://ftp.suse.com/pub/projects/security/osv/openSUSE-SU-2024:10066-1.json"
      },
      "ecosystem_specific": {
        "binaries": [
          {
            "python-Django": "1.9.12-1.1"
          }
        ]
      },
      "package": {
        "ecosystem": "openSUSE:Tumbleweed",
        "name": "python-Django",
        "purl": "pkg:rpm/opensuse/python-Django&distro=openSUSE%20Tumbleweed"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.9.12-1.1"
            }
          ],
          "type": "ECOSYSTEM"
        }
      ],
      "versions": []
    }
  ],
  "details": "These are all security issues fixed in the python-Django-1.9.12-1.1 package on the GA media of openSUSE Tumbleweed.",
  "id": "openSUSE-SU-2024:10066-1",
  "modified": "2025-05-07T18:09:08.965365Z",
  "published": "2024-06-15T00:00:00Z",
  "references": [
    {
      "type": "ADVISORY"
    },
    {
      "type": "WEB",
      "url": "https://www.suse.com/security/cve/CVE-2015-3982"
    },
    {
      "type": "WEB",
      "url": "https://www.suse.com/security/cve/CVE-2015-5145"
    },
    {
      "type": "WEB",
      "url": "https://www.suse.com/security/cve/CVE-2015-5963"
    }
  ],
  "related": [
    "CVE-2015-3982",
    "CVE-2015-5145",
    "CVE-2015-5963"
  ],
  "schema_version": "1.6.0",
  "summary": "python-Django-1.9.12-1.1 on GA media",
  "upstream": [
    "CVE-2015-3982",
    "CVE-2015-5145",
    "CVE-2015-5963"
  ]
}