{
  "affected": [
    {
      "database_specific": {
        "source": "https://ftp.suse.com/pub/projects/security/osv/SUSE-SU-2025:02787-1.json"
      },
      "ecosystem_specific": {
        "binaries": [
          {
            "libpython3_6m1_0": "3.6.15-150000.3.185.1",
            "python3": "3.6.15-150000.3.185.2",
            "python3-base": "3.6.15-150000.3.185.1"
          }
        ]
      },
      "package": {
        "ecosystem": "SUSE:Linux Enterprise Micro 5.1",
        "name": "python3",
        "purl": "pkg:rpm/suse/python3&distro=SUSE%20Linux%20Enterprise%20Micro%205.1"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.6.15-150000.3.185.2"
            }
          ],
          "type": "ECOSYSTEM"
        }
      ],
      "versions": []
    },
    {
      "database_specific": {
        "source": "https://ftp.suse.com/pub/projects/security/osv/SUSE-SU-2025:02787-1.json"
      },
      "ecosystem_specific": {
        "binaries": [
          {
            "libpython3_6m1_0": "3.6.15-150000.3.185.1",
            "python3": "3.6.15-150000.3.185.2",
            "python3-base": "3.6.15-150000.3.185.1"
          }
        ]
      },
      "package": {
        "ecosystem": "SUSE:Linux Enterprise Micro 5.1",
        "name": "python3-core",
        "purl": "pkg:rpm/suse/python3-core&distro=SUSE%20Linux%20Enterprise%20Micro%205.1"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.6.15-150000.3.185.1"
            }
          ],
          "type": "ECOSYSTEM"
        }
      ],
      "versions": []
    }
  ],
  "details": "This update for python3 fixes the following issues:\n\n- CVE-2025-8194: Fixed denial of service caused by tar archives with negative offsets (bsc#1247249).  \n",
  "id": "SUSE-SU-2025:02787-1",
  "modified": "2025-08-13T19:18:33.191581Z",
  "published": "2025-08-13T11:51:30Z",
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://www.suse.com/support/update/announcement/2025/suse-su-202502787-1/"
    },
    {
      "type": "REPORT",
      "url": "https://bugzilla.suse.com/1247249"
    },
    {
      "type": "WEB",
      "url": "https://www.suse.com/security/cve/CVE-2025-8194"
    }
  ],
  "related": [
    "CVE-2025-8194"
  ],
  "schema_version": "1.7.3",
  "summary": "Security update for python3",
  "upstream": [
    "CVE-2025-8194"
  ]
}